# Generated by Django 5.2.5 on 2025-08-24 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chauffeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('prenom', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('numero_permis', models.CharField(blank=True, max_length=50)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif')], default='actif', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('immatriculation', models.CharField(max_length=30, unique=True)),
                ('marque', models.CharField(blank=True, max_length=50)),
                ('modele', models.CharField(blank=True, max_length=50)),
                ('capacite_passagers', models.PositiveIntegerField(default=0)),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('maintenance', 'Maintenance')], default='disponible', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('origine', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('depart_datetime', models.DateTimeField()),
                ('arrivee_datetime', models.DateTimeField()),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='planifie', max_length=20)),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transport.chauffeur')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transport.vehicule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('nom_client', models.CharField(max_length=100)),
                ('telephone_client', models.CharField(blank=True, max_length=30)),
                ('nombre_passagers', models.PositiveIntegerField(default=1)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('trajet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='transport.trajet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
